import { FastifyInstance, FastifyRequest } from "fastify";
import { Task3OrganizationService, BossDirectionService } from "../application/task3.js";
import { InvalidArgumentError, InvalidMessageError } from "../domain/errors.js";
import { validateSafeValue } from "../domain/common.js";
import { assertLocalRequest } from "../security/local-access.js";
import { Action, ExecutionGrant, StructuredPlan } from "../policy/types.js";

/** 注册 Task 3 组织、角色、结构化消息、策略和 Boss 方向交接 API。 */
export function registerTask3Routes(app: FastifyInstance, options: { testMode: boolean }): void {
  const service = new Task3OrganizationService(app.runtime.database);
  const directions = new BossDirectionService(app.runtime.database);
  app.get("/api/v1/organization", async (request) => { const traceId = `tr_organization_${Date.now().toString(36)}`; assertLocalRequest(request, options.testMode, traceId); return service.getOrganization(); });
  app.get("/api/v1/roles", async (request) => { const traceId = `tr_roles_${Date.now().toString(36)}`; assertLocalRequest(request, options.testMode, traceId); return { roles: service.listRoles(), version: 1 }; });
  app.get("/api/v1/roles/:roleId", async (request) => { const traceId = `tr_role_${Date.now().toString(36)}`; assertLocalRequest(request, options.testMode, traceId); const roleId = String((request.params as { roleId?: string }).roleId ?? ""); if (!roleId) throw new InvalidArgumentError("roleId 不能为空", { traceId }); return service.getRole(roleId); });
  app.get("/api/v1/organization/office-view", async (request) => { const traceId = `tr_office_${Date.now().toString(36)}`; assertLocalRequest(request, options.testMode, traceId); return service.getOfficeView(); });
  app.post("/api/v1/messages", async (request, reply) => { const traceId = `tr_message_${Date.now().toString(36)}`; assertLocalRequest(request, options.testMode, traceId); const message = service.sendMessage(request.body); reply.code(201); return message; });
  app.get("/api/v1/messages", async (request) => { const traceId = `tr_messages_${Date.now().toString(36)}`; assertLocalRequest(request, options.testMode, traceId); const query = parseMessageQuery(request, traceId); return service.listMessages(query); });
  app.post("/api/v1/messages/:messageId/acknowledge", async (request) => { const traceId = `tr_message_ack_${Date.now().toString(36)}`; assertLocalRequest(request, options.testMode, traceId); const messageId = String((request.params as { messageId?: string }).messageId ?? ""); const body = (request.body ?? {}) as Record<string, unknown>; const handledBy = validateSafeValue(String(body.handledBy ?? ""), "handledBy"); return service.acknowledgeMessage(messageId, handledBy); });
  app.post("/api/v1/approvals/:approvalId/direction", async (request) => { const traceId = `tr_direction_${Date.now().toString(36)}`; assertLocalRequest(request, options.testMode, traceId); const approvalId = String((request.params as { approvalId?: string }).approvalId ?? ""); const body = (request.body ?? {}) as Record<string, unknown>; const directionOpinion = String(body.directionOpinion ?? ""); const assignedLead = body.assignedLead as { roleId?: string; instanceId?: string } | undefined; if (!assignedLead) throw new InvalidMessageError("assignedLead 不能为空", { traceId }); return directions.convert({ approvalId, directionOpinion, assignedLead: { roleId: String(assignedLead.roleId ?? ""), instanceId: String(assignedLead.instanceId ?? "") }, responseArtifactRequired: body.responseArtifactRequired === false ? false : true }); });
  app.post("/api/v1/policy/authorize-action", async (request, reply) => { const traceId = `tr_policy_${Date.now().toString(36)}`; assertLocalRequest(request, options.testMode, traceId); const body = (request.body ?? {}) as { roleId?: string; action?: Action; grant?: ExecutionGrant }; if (!body.roleId || !body.action || !body.grant) throw new InvalidArgumentError("roleId、action 和 grant 均不能为空", { traceId }); const decision = await service.authorizeAction(body.roleId, body.action, body.grant); await auditPolicy(app, decision); reply.code(decision.decision === "allow" ? 200 : 403); return decision; });
  app.post("/api/v1/policy/evaluate-plan", async (request, reply) => { const traceId = `tr_policy_plan_${Date.now().toString(36)}`; assertLocalRequest(request, options.testMode, traceId); const body = (request.body ?? {}) as { roleId?: string; task?: { id: string; projectId: string; ownerRole: string; version: number }; plan?: StructuredPlan; grant?: ExecutionGrant }; if (!body.roleId || !body.task || !body.plan || !body.grant) throw new InvalidArgumentError("roleId、task、plan 和 grant 均不能为空", { traceId }); const decision = await service.evaluatePlan(body.roleId, body.task, body.plan, body.grant); await auditPolicy(app, decision); reply.code(decision.decision === "allow" ? 200 : 403); return decision; });
}

/** 解析消息列表参数并拒绝隐藏的过滤条件，保证分页行为可审计。 */
function parseMessageQuery(request: FastifyRequest, traceId: string): { projectId: string | null; taskId: string | null; limit: number; cursor: string | null } {
  const params = new URL(request.raw.url ?? "/", "http://localhost").searchParams; const allowed = new Set(["projectId", "taskId", "limit", "cursor"]); const unknown = [...new Set([...params.keys()].filter((key) => !allowed.has(key)))]; if (unknown.length) throw new InvalidArgumentError("unsupported message query parameter", { traceId, data: { parameters: unknown } }); const projectId = params.get("projectId"); const taskId = params.get("taskId"); const cursor = params.get("cursor"); const limit = params.get("limit") ? Number(params.get("limit")) : 100; if (!Number.isInteger(limit) || limit < 1 || limit > 500) throw new InvalidArgumentError("limit must be between 1 and 500", { traceId }); return { projectId: projectId?.trim() || null, taskId: taskId?.trim() || null, limit, cursor: cursor?.trim() || null };
}

/** 将拒绝结果同步写入脱敏安全事件，策略拒绝不能只停留在 HTTP 响应中。 */
async function auditPolicy(app: FastifyInstance, decision: { decision: string; traceId: string; roleId: string; policyVersion: number; reason: string }): Promise<void> { if (decision.decision !== "allow") await app.runtime.audit.write({ traceId: decision.traceId, eventType: "SecurityPolicyDenied", result: "blocked", metadata: { roleId: decision.roleId, policyVersion: decision.policyVersion, reason: decision.reason } }); }
